### PR TITLE
Create api with rails

### PR DESCRIPTION
**Pull request by Fsher07**
- Create a new Rails API app called 'hello-rails-back-end'.
 - Initialize your project with Git.
 - Make sure that your project has a Postgres database set up. 
 - Create a table for storing your messages and create 5 different greetings. 
 - Create an API endpoint that selects a random greeting from your table (you will need a controller with an action an rails route).

I know there should be no linter errors but my workflow is stuck in the queue. I couldn't find a certain solution for this one.

[Front-end with React](https://github.com/Fsher07/react-front-end)

### CODE REVIEW

**Review by FrederickMih — COMMENTED** [review]
Hi @Fsher07 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

> You have submitted a project with the following issues:
> - GitHub action is not enabled
> - No descriptive README file in both frontend and backend of your project.
> - Based on the requirements of this project, in the README file of the backend, you should add a link to the frontend part and in the README file of the frontend, you should add a link to the Rails API(backend). 
> - PR should be created for both frontend and the backend.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Fsher07** [comment]
Hello @FrederickMih,
As I mentioned in the PR description, "I know there should be no linter errors but my workflow is stuck in the queue. I couldn't find a certain solution for this one.".
I already created PRs for both the front-end and back-end parts. 
Yes, I should create a descriptive README file for both of them and add a link to the front-end's README file.

**Review by FrederickMih — CHANGES_REQUESTED** [review]
Hi @Fsher07 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



##Highlighs

- No Linter issue detected :heavy_check_mark: 
- PR has a title and description :heavy_check_mark: 
- Correct GitHub workflow :heavy_check_mark: 
- Endpoint for returning random greeting was created :heavy_check_mark: 

## Required Changes ♻️

- [ ] Hi @Fsher07, based on the requirements of this project, the two apps should work together. When I change the API URL in the React app and check on my localhost no random greetings were displayed. Kindly make sure that our apps connect successively. 

**NB** I Ieft some comments in the frontend PR thread, kindly check and also fix them.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Fsher07** [comment]
Hello @FrederickMih ,
I did not get the point. It locally works for me. Also, I did not see any review in my front-end PR thread.

**Comment by FrederickMih** [comment]
> Hello @FrederickMih , I did not get the point. It locally works for me. Also, I did not see any review in my front-end PR thread.

Hi @Fsher07, I'm sorry for the late reply. Please can you check the frontend PR once more?

**Review by ahmetbozaci — CHANGES_REQUESTED** [review]
# ♻️♻️♻️ STATUS: Changes Required  ♻️♻️♻️ 


@Fsher07  ✋🏼 
#### Great work on making the changes requested by a previous reviewer 👏 
#### You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
___ 

### 💯  Highlights 💯
- Your git-flow is correct. ✔️
- You set up linter files and no errors. ✔️
- Your pull request is very professional. It has a meaningful title and summary. Keep it up.✔️
___

### ♻️ Request changes ♻️

- [ ] _Check the comments under the review._
- [x] Rails server working well. But like the last code reviewer said ı cant see any message on the react side. Kindly fix it.
___

### Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- [ ] It will be better if you add some samples to the seed file. Otherwise, the user should create it.
### Example
image

___

### Cheers and Happy coding! 💻 👏
almost


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._
___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

**Comment by Fsher07** [comment]
Hi @ahmetbozaci, 
Can you come to a zoom call? As said before, it works and there is no problem from my perspective. That's why I do not know what you are going through when you run it.

**Comment by ahmetbozaci** [comment]
> Hi @ahmetbozaci, Can you come to a zoom call? As said before, it works and there is no problem from my perspective. That's why I do not know what you are going through when you run it.

@Fsher07 Answered on slack.

**Review by rustam-tolipov — APPROVED** [review]
## Hello @Fsher07 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

Developer-512px-10

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
